export const brands = [
  { id: 'tesla', name: 'Tesla', slug: 'tesla', logo: '/brand-logos/tesla-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Tesla logo', services: ['ECM Repair', 'Hybrid Battery', 'Car Programming'] },
  { id: 'byd', name: 'BYD', slug: 'byd', logo: '/brand-logos/byd-1.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'BYD logo', services: ['Hybrid Battery', 'Car Programming', 'General Repair'] },
  { id: 'bmw', name: 'BMW', slug: 'bmw', logo: '/brand-logos/bmw-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'BMW logo', services: ['ECM Repair', 'Car Programming', 'ABS & Airbag'] },
  { id: 'mercedes', name: 'Mercedes-Benz', slug: 'mercedes', logo: '/brand-logos/mercedes-benz-alt-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Mercedes-Benz logo', services: ['ECM Repair', 'Car Programming', 'Electrical Repair'] },
  { id: 'audi', name: 'Audi', slug: 'audi', logo: '/brand-logos/audi-11-logo-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Audi logo', services: ['ECM Repair', 'Car Programming', 'General Repair'] },
  { id: 'nissan', name: 'Nissan', slug: 'nissan', logo: '/brand-logos/nissan-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Nissan logo', services: ['ECM Repair', 'Hybrid Battery', 'General Repair'] },
  { id: 'toyota', name: 'Toyota', slug: 'toyota', logo: '/brand-logos/toyota-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Toyota logo', services: ['Hybrid Battery', 'General Repair', 'AC Repair'] },
  { id: 'honda', name: 'Honda', slug: 'honda', logo: '/brand-logos/honda-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Honda logo', services: ['ECM Repair', 'General Repair', 'AC Repair'] },
  { id: 'hyundai', name: 'Hyundai', slug: 'hyundai', logo: '/brand-logos/hyundai-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Hyundai logo', services: ['ECM Repair', 'General Repair', 'Electrical Repair'] },
  { id: 'kia', name: 'Kia', slug: 'kia', logo: '/brand-logos/kia-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Kia logo', services: ['ECM Repair', 'General Repair', 'AC Repair'] },
  { id: 'ford', name: 'Ford', slug: 'ford', logo: '/brand-logos/ford-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Ford logo', services: ['ECM Repair', 'General Repair', 'ABS & Airbag'] },
  { id: 'chevrolet', name: 'Chevrolet', slug: 'chevrolet', logo: '/brand-logos/chevrolet-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Chevrolet logo', services: ['ECM Repair', 'General Repair', 'Electrical Repair'] },
  { id: 'volkswagen', name: 'Volkswagen', slug: 'volkswagen', logo: '/brand-logos/volkswagen-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Volkswagen logo', services: ['ECM Repair', 'Car Programming', 'General Repair'] },
  { id: 'lexus', name: 'Lexus', slug: 'lexus', logo: '/brand-logos/lexus-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Lexus logo', services: ['Hybrid Battery', 'General Repair', 'AC Repair'] },
  { id: 'mazda', name: 'Mazda', slug: 'mazda', logo: '/brand-logos/mazda-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Mazda logo', services: ['ECM Repair', 'General Repair', 'AC Repair'] },
  { id: 'subaru', name: 'Subaru', slug: 'subaru', logo: '/brand-logos/subaru-svgrepo-com.svg', logoWidth: 120, logoHeight: 120, logoAlt: 'Subaru logo', services: ['ECM Repair', 'General Repair', 'Electrical Repair'] },
]

export const brandDetails: Record<string, any> = {
  tesla: {
    name: 'Tesla',
    description: 'Tesla repair and programming specialists in Dubai. We service Model S, Model 3, Model X, and Model Y with expert ECM repair, battery diagnostics, and online programming.',
    services: ['ECM Repair', 'Hybrid Battery Diagnostics', 'Car Programming', 'Electrical Repair'],
    certifications: ['Tesla Certified Technician', 'Advanced Diagnostics'],
  },
  byd: {
    name: 'BYD',
    description: 'BYD electric and hybrid vehicle specialists. We provide battery repair, ECM programming, and comprehensive diagnostics for all BYD models.',
    services: ['Hybrid Battery Repair', 'ECM Programming', 'General Repair', 'Electrical Systems'],
    certifications: ['BYD Authorized Service', 'EV Specialist'],
  },
  bmw: {
    name: 'BMW',
    description: 'BMW repair and programming experts in Ras Al Khor. We handle ECM repair, gear programming, and advanced diagnostics for all BMW models.',
    services: ['ECM Repair & Programming', 'Gear Programming', 'ABS & Airbag Repair', 'General Repair'],
    certifications: ['BMW Diagnostic Certified', 'Advanced Programming'],
  },
  mercedes: {
    name: 'Mercedes-Benz',
    description: 'Mercedes-Benz specialist repair and programming. We service all models with expert ECM repair, electrical diagnostics, and programming.',
    services: ['ECM Repair', 'Electrical Repair', 'Car Programming', 'General Repair'],
    certifications: ['Mercedes Diagnostic Certified', 'Advanced Technician'],
  },
  audi: {
    name: 'Audi',
    description: 'Audi repair and programming specialists. We provide ECM repair, car programming, and comprehensive diagnostics for all Audi models.',
    services: ['ECM Repair & Programming', 'Car Programming', 'General Repair', 'Electrical Repair'],
    certifications: ['Audi Diagnostic Certified', 'Programming Specialist'],
  },
  nissan: {
    name: 'Nissan',
    description: 'Nissan repair specialists including hybrid models. We service ECM repair, hybrid battery diagnostics, and general maintenance.',
    services: ['ECM Repair', 'Hybrid Battery Repair', 'General Repair', 'AC Repair'],
    certifications: ['Nissan Certified', 'Hybrid Specialist'],
  },
  toyota: {
    name: 'Toyota',
    description: 'Toyota and hybrid vehicle specialists. We provide hybrid battery repair, general maintenance, and AC repair for all Toyota models.',
    services: ['Hybrid Battery Repair', 'General Repair', 'AC Repair', 'Electrical Repair'],
    certifications: ['Toyota Certified', 'Hybrid Specialist'],
  },
  honda: {
    name: 'Honda',
    description: 'Honda repair and diagnostics specialists. We service ECM repair, general maintenance, and AC repair for all Honda models.',
    services: ['ECM Repair', 'General Repair', 'AC Repair', 'Electrical Repair'],
    certifications: ['Honda Certified', 'Diagnostic Specialist'],
  },
  hyundai: {
    name: 'Hyundai',
    description: 'Hyundai repair and programming specialists. We provide ECM repair, general maintenance, and electrical diagnostics.',
    services: ['ECM Repair', 'General Repair', 'Electrical Repair', 'AC Repair'],
    certifications: ['Hyundai Certified', 'Diagnostic Specialist'],
  },
  kia: {
    name: 'Kia',
    description: 'Kia repair specialists. We service ECM repair, general maintenance, and AC repair for all Kia models.',
    services: ['ECM Repair', 'General Repair', 'AC Repair', 'Electrical Repair'],
    certifications: ['Kia Certified', 'Diagnostic Specialist'],
  },
  ford: {
    name: 'Ford',
    description: 'Ford repair and diagnostics specialists. We provide ECM repair, ABS & airbag repair, and general maintenance.',
    services: ['ECM Repair', 'General Repair', 'ABS & Airbag Repair', 'Electrical Repair'],
    certifications: ['Ford Certified', 'Diagnostic Specialist'],
  },
  chevrolet: {
    name: 'Chevrolet',
    description: 'Chevrolet repair specialists. We service ECM repair, general maintenance, and electrical diagnostics.',
    services: ['ECM Repair', 'General Repair', 'Electrical Repair', 'AC Repair'],
    certifications: ['Chevrolet Certified', 'Diagnostic Specialist'],
  },
  volkswagen: {
    name: 'Volkswagen',
    description: 'Volkswagen repair and programming specialists. We provide ECM repair, car programming, and general maintenance.',
    services: ['ECM Repair & Programming', 'Car Programming', 'General Repair', 'Electrical Repair'],
    certifications: ['VW Certified', 'Programming Specialist'],
  },
  lexus: {
    name: 'Lexus',
    description: 'Lexus and hybrid vehicle specialists. We provide hybrid battery repair, general maintenance, and AC repair.',
    services: ['Hybrid Battery Repair', 'General Repair', 'AC Repair', 'Electrical Repair'],
    certifications: ['Lexus Certified', 'Hybrid Specialist'],
  },
  mazda: {
    name: 'Mazda',
    description: 'Mazda repair specialists. We service ECM repair, general maintenance, and AC repair for all Mazda models.',
    services: ['ECM Repair', 'General Repair', 'AC Repair', 'Electrical Repair'],
    certifications: ['Mazda Certified', 'Diagnostic Specialist'],
  },
  subaru: {
    name: 'Subaru',
    description: 'Subaru repair specialists. We provide ECM repair, general maintenance, and electrical diagnostics.',
    services: ['ECM Repair', 'General Repair', 'Electrical Repair', 'AC Repair'],
    certifications: ['Subaru Certified', 'Diagnostic Specialist'],
  },
}
